### PR TITLE
Fix cutils location

### PR DESCRIPTION
**Pull request by whitews**
Fixes issue #150 where cutils extension was compiled to the directory above the package directory.  

Note, this bumps to beta version 1.1.6b0

### CODE REVIEW

**Comment by whitews** [comment]
There seems to be some different behavior in the `pip install .` and maybe running pytest as a module instead of running directly. I'll try running directly and see if that works. The other option is to force the `build_ext --inplace`.

**Comment by whitews** [comment]
Hi Tommy,

If everything looks good to you & assuming the tests pass for the last commit, this PR should be good to go.

-Scott

**Comment by tommyod** [comment]
Great, thanks a lot for the work. Formatting seems to fail, but that's a quick fix. 

I'll approve and merge once formatting is OK.
One other thing - could we just call it version `1.1.7`? That way we don't have to introduce beta versions to the project, which have not been used before I think.

> Curious what you think?

I don't have any strong opinions :) Very happy that you bothered to look into this.

**Comment by whitews** [comment]
Ok, fixed the formatting & went to 1.1.6 (seems to be the next version, correct me if not). Should I also just fix the matplotlib dep issue in this PR or would you prefer a separate one?

**Pull request merged**
