### PR TITLE
Re-org CI workflows

### PR DESCRIPTION
**Pull request by whitews**
Hi Tommy,

Spent some time learning about GH Actions & came up these proposed changes. The main motivation was to add wheels for Apple Silicon Macs (arm64), Linux, & for the new Python 3.12 release. In doing this I also separated the functionality of testing from the building & publishing to PyPI. 

The 'build' workflow is configured to be triggered manually. I know you mentioned having everything automated, but this allows more flexibility in updating before actually releasing something to PyPI. The publishing is also configured to be dependent on all the wheels & source package being built so would prevent a partial release to PyPI.

Let me know if there are any questions or requests to change something. Also, the CI system is very finicky so until it actually runs on your side there may be some tweaking needed which I'm happy to do.

Regards,
Scott

### CODE REVIEW

**Comment by tommyod** [comment]
Hi Scott! Thanks for this!

> The main motivation was to add wheels for Apple Silicon Macs (arm64), Linux, & for the new Python 3.12 release. 

Great stuff!

> I know you mentioned having everything automated, but this allows more flexibility in updating before actually releasing something to PyPI.

Alright. I'm willing to try that out.

> Let me know if there are any questions or requests to change something. Also, the CI system is very finicky so until it actually runs on your side there may be some tweaking needed which I'm happy to do.

Everything looks good from my side. No big questions. But I haven't done work on the CI system for some time. My only (nitpick) comment would be to decide on underscore vs dash in the filenames. Let's merge this into `develop` when you're ready, then we see what happens.

Give me a heads-up when you're ready to merge. (you might already be, but I wanted to confirm before merging) :+1:

**Comment by whitews** [comment]
> decide on underscore vs dash in the filenames

Good catch, surprised my OCD let that through. Oh, and what about the travis directory & script, ok to remove?

**Comment by tommyod** [comment]
Yes. Please do remove everything related to Travis. Only GH actions should be in use :)

**Comment by whitews** [comment]
Alright, I think we can give it a try! :crossed_fingers:

**Comment by whitews** [comment]
Looks like it worked! However, those job names for the matrix aren't super helpful...would be nice to see the python version. I'll see if I can fix that.

**Pull request merged**
