### PR TITLE
Update FFTKDE.py

### PR DESCRIPTION
**Pull request by mathematicalmichael**
evaluating a KDE on the original set of samples is a _very_ common scenario, and there's absolutely no reason to prevent it from being done with this package.

### CODE REVIEW

**Comment by mathematicalmichael** [comment]
ah okay, didn't realize the evaluation grid _needed_ to be equidistant. 
That's a shame. I love the speed this provides, and if it was able to evaluate on the original data, it would be perfect for some of my projects.

**Comment by tommyod** [comment]
That's the trade-off essentially: very fast computation is only possible if the grid is equidistant.

**Comment by mathematicalmichael** [comment]
such a shame. I ended up going down a rabbit-hole coding up Gaussian KDE in C++ and found it only marginally faster than scipy, with the added overhead of I/O to pass back to the python code eliminating most advantages for large sample sizes. Choosing a kernel that's faster to evaluate helps a lot with the C++ speed, but ultimately sometimes Gaussian has the right theory behind it. 

I think the delicate balance is using a lower sample size for defining the KDE estimate and evaluating it at the full set of samples. I did a complexity analysis on it and the payoff of choosing good samples is easily the best way to speed up computation. If you have any suggestions for alternatives for KDE

**Comment by tommyod** [comment]
Everything you write sounds reasonable.

Before writing this library I used to just downsample the data when creating KDE plots. Whether I use 5 million or 5000 data points does not matter much in most cases. Ultimately what lead me to write this library was my desire to assign weights to data points. Since I was writing it from scratch, I also tried to make it fast. For plotting purposes equidistant sampling points make a lot of sense, and I suppose 90 %+ of use cases are plotting.

**Comment by mathematicalmichael** [comment]
ah I see. 
Yes, you're probably correct. I, unfortunately, am in the minority there, as my theoretical work relies on density estimation to characterize the probabilities of events. 

One of the things I quickly tried was using the regular samples + nearest neighbors to form a piece-wise simple-function approximation to the density. There's theory to support this working, but in practice makes results just a bit harder to deal with.

**Pull request closed without merging**
