### PR TITLE
Replaced numpy.asfarray with numpy.asarray using the proper dtype.

### PR DESCRIPTION
**Pull request by SergejKr**
I executed the unit tests with python 3.9 and 3.12. Everything was okay.

### CODE REVIEW

**Comment by tommyod** [comment]
Can you explain why this is needed?

Some tests are failing. Please take a look

**Comment by SergejKr** [comment]
Hi. The asfarray is deprecated in numpy >= 2. To use KDEpy with numpy >= 2 it must be replaced with asarray.

Why the test fail, I dont know though. I will have a look.

**Comment by tommyod** [comment]
Great, thanks!

**Comment by SergejKr** [comment]
I Solved the issues for the windows builds. It seems that for ubuntu and macOS, there is some other version of the KDEpy package. For example, the source code of test_cython_binning on the master is:

````
   @pytest.mark.parametrize(
        "dims, use_weights, eq_grid",
        itertools.product([1, 2, 3, 4], [True, False], [True, False]),
    )
    def test_cython_binning(self, dims, use_weights, eq_grid):
        """
        Test the fast N-dimensional binning up against the naive
        Python implementation - using weights, no weights, equal grid values
        in each direction and unequal ones.
        """

        num_points = 1000
        data = np.random.randn(dims * num_points).reshape(num_points, dims) / 7

        if use_weights:
            weights = np.random.randn(num_points)
        else:
            weights = None

        if eq_grid:
            num_points = (16,) * dims
        else:
            num_points = tuple([random.randint(8, 16) for i in range(dims)])

        grid_points = autogrid(np.array([[0] * dims]), num_points=num_points)
        result = linear_binning(data, grid_points, weights=weights)
        result_slow = linbin_Ndim_python(data, grid_points, weights=weights)

        assert np.allclose(result, result_slow)
```

The source code for this method in the error messages for any ubuntu or macOS build is different.

**Comment by SergejKr** [comment]
Changed dtype from int32 to long. Hope it solves also the issues on macOS and Ubuntu

**Comment by SergejKr** [comment]
All checks have passed. Do you need anything else from me?

**Comment by tommyod** [comment]
Merged! Thanks for the contribution @SergejKr !

**Pull request merged**
