### PR TITLE
py39

### PR DESCRIPTION
**Pull request by tommyod**

### CODE REVIEW

**Comment by psmgeelen** [comment]
Hi there, I would LOVE support for Py3.9. What is the timeline on that? Could I be supportive in anyway? BTW: Awesome library! It was a game changer to implement KDE efficiently.

**Comment by tommyod** [comment]
Hi @psmgeelen . There's no specific timeline. Right now py39 fails, as you can see from the GH action on this PR. I am not sure why it fails, it seems to be some problem with building the cython code (?). It works on all versions apart from py39.

Once this PR passes on py39, either because (1) a change is made upstream to one or more packages, or (2) someone investigates and fixes a potential problem with this code, then I will merge and we'll have py39 support. I don't have a lot of free time to look into this, and I am personally in no rush to use KDEpy on py39. 

So if you want to investigate this issue I would greatly appreciate it.

**Comment by psmgeelen** [comment]
Hi @tommyod, lets do it! Is there anything I need to know or have access too? Or do I debug on my own accord?

**Comment by tommyod** [comment]
See if you have access to the GH actions [build logs](https://github.com/tommyod/KDEpy/runs/2552609214?check_suite_focus=true). You should be able to see on the left side that everything passes except py39, and that there is an error in "Run tests and linting." That's all I know. I'm happy to help out, but honestly I don't know much - I think googling might be the best approach.

**Comment by psmgeelen** [comment]
@tommyod , Ill get on it!

**Comment by psmgeelen** [comment]
In python 3.9 the function ```tp_print``` has been discontinued.
https://docs.python.org/dev/whatsnew/3.9.html#build-and-c-api-changes

It seems that is has been replaced with ```tp_vectorcall_offset```. I gathered this from several forums and the literal replacement here:
https://github.com/python/cpython/commit/530f506ac91338b55cf2be71b1cdf50cb077512f
And the documentation here:
https://www.python.org/dev/peps/pep-0590/#:~:text=The%20unused%20slot%20printfunc%20tp_print,It%20has%20the%20type%20Py_ssize_t.&text=The%20tp_print%20slot%20is%20reused,protocol%20to%20earlier%20Python%20versions.

Similar issues have been noted with Numpy: https://github.com/numpy/numpy/issues/17937

When straight up replacing ```tp_print``` to ```tp_vectorcall_offset``` in the cutils.c file it does change the error into: 

```
 gcc -pthread -B /home/pieter/anaconda3/envs/p39/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/pieter/anaconda3/envs/p39/include -fPIC -O2 -isystem /home/pieter/anaconda3/envs/p39/include -fPIC -I/home/pieter/anaconda3/envs/p39/lib/python3.9/site-packages/numpy/core/include -I/home/pieter/anaconda3/envs/p39/include/python3.9 -c KDEpy/cutils.c -o build/temp.linux-x86_64-3.9/KDEpy/cutils.o
  KDEpy/cutils.c: In function ‘__Pyx_modinit_type_init_code’:
  KDEpy/cutils.c:18644:26: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_vectorcall_offsett’; did you mean ‘tp_vectorcall_offset’?
  18644 |   __pyx_type___pyx_array.tp_vectorcall_offsett = 0;
        |                          ^~~~~~~~~~~~~~~~~~~~~
        |                          tp_vectorcall_offset
  KDEpy/cutils.c:18649:32: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_vectorcall_offsett’; did you mean ‘tp_vectorcall_offset’?
  18649 |   __pyx_type___pyx_MemviewEnum.tp_vectorcall_offsett = 0;
        |                                ^~~~~~~~~~~~~~~~~~~~~
        |                                tp_vectorcall_offset
  KDEpy/cutils.c:18664:31: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_vectorcall_offsett’; did you mean ‘tp_vectorcall_offset’?
  18664 |   __pyx_type___pyx_memoryview.tp_vectorcall_offsett = 0;
        |                               ^~~~~~~~~~~~~~~~~~~~~
        |                               tp_vectorcall_offset
  KDEpy/cutils.c:18677:36: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_vectorcall_offsett’; did you mean ‘tp_vectorcall_offset’?
  18677 |   __pyx_type___pyx_memoryviewslice.tp_vectorcall_offsett = 0;
        |                                    ^~~~~~~~~~~~~~~~~~~~~
        |                                    tp_vectorcall_offset
  KDEpy/cutils.c: In function ‘__Pyx_ParseOptionalKeywords’:
  KDEpy/cutils.c:19320:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  19320 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                     ^
```

I probably botching something here, but I will need more time to figure this out. If you have any ideas on the matter, please share :) It seems that this is a generic issues of which I am missing the obvious solution atm..

**Comment by tommyod** [comment]
Thanks! It's still not exactly clear to me what exactly is going on. Maybe a specific version of cython should be used with py39. I think a sensible way forward is to fork KDEpy, create a py39 env locally and see if installing from source (use the same commands as in the GH actions file) works with the newest version of cython (or maybe some cython flag has to be turned on? or something like that).

**Comment by psmgeelen** [comment]
Lets see, seems we are looking into the right direction https://github.com/cython/cython/pull/3186. Ill test with a newer version now

**Comment by psmgeelen** [comment]
So I upped the requirements text to ```cython>=0.29```, removed the cutils.c (which ought to be the cythonised version of the cutils.pyx. After that I installed it, and it works! So should be easy :) I ran all your py test and did a FFTKDE for good measure to validate. Anything else I can support you with?

**Comment by tommyod** [comment]
Fantastic work @psmgeelen . Thanks a lot for showing initiative. I'll try to do the same, then report back in this PR :)

**Comment by tommyod** [comment]
[KDEpy now works with py39](https://pypi.org/project/KDEpy/1.0.11/#files). The culprit was the .c file I had committet to the repo. Again thanks a lot @psmgeelen , I appreciate the time you took to solve this.

**Pull request merged**
