### PR TITLE
Bandwidth weights

### PR DESCRIPTION
**Pull request by lukedyer-peak**
Often when you're using a weighted KDE you also want the bandwidth to respect the weights.  For instance if some far out samples have a small weight we wouldn't want them to massively increased the bandwidth.  I've done the easy win of implementing the weighting for the ISJ bandwidth as well as cleaning up a bit of duplicate code around creating the bandwidth in the subclasses.

I've left the other two bandwidths (Scott & Silverman's) as just giving warnings if weights are given.  I haven't though too much about these ones but extending the weighting is probably a lot more complicated and involved.

I also haven't added any tests as of yet.  Dependent if you think this PR is useful.  I'm also not sure if there are any existing unit tests for the `bw_selection.py` functions.  There are some tests in the `test_api.py` but they're more integration tests.  Please just advise me on this.

### CODE REVIEW

**Comment by tommyod** [comment]
First of all - great work. I did not catch this when I wrote the code. Great to see quality contributions.

I think a few tests such as
```pyton
improved_sheather_jones([0] * 100 + [1] * 200, weights=None) == improved_sheather_jones([0, 1], weights=[1, 2])
```
would be useful here. Use `np.allclose` instead of `==` to compare floats. Include a few variations of the test above. Also, test that trivial unit weights have the same effect as no weights, etc.

**Comment by lukedyer-peak** [comment]
Thanks for the quick reply.  For the above property test I would generally use [hypothesis](https://hypothesis.readthedocs.io/en/latest/).  However, would add an extra testing dependency to the project so just wanted to check you'd be ok with that?  Otherwise I can just do some examples as you've suggested above.  Happy either way and it's your call.

**Comment by tommyod** [comment]
My vote is to keep it easy - make a few examples by hand and avoid another dependency. The ISJ optimization will fail with too few data points, so it might be more robust to make some test cases by hand. If you disagree, then adding the dependency is fine too, but then I suppose it should be used for all tests. There are some other property tests too, which I just created by hand. :+1:

**Comment by lukedyer-peak** [comment]
@tommyod I've added in some tests now and it's ready for a review 🤞 .

Just to note I'm not sure if you allow weights to be 0 elsewhere in this package.  I couldn't see it documented either way but could have easily missed it.  I've allowed it in this case but can remove that support if you think it would fit better in the package without it.

I also didn't run black on the whole project as I didn't want the lines changed to be huge.

**Comment by tommyod** [comment]
The PR looks good. I see that Travis branches did not report the build. I have to look into that too, so I probably won't find time to merge immediately. Thanks a lot again for the code. I'll merge the branch soon :)

**Comment by lukedyer-peak** [comment]
Thanks for the quick and helpful review.  It makes it nice to contribute code 😄

**Pull request merged**
